### ISSUE TITLE
Lowercase delta and omega have uppercase glyphs

### ISSUE THREAD

**Issue by dscorbett** [SorkinType/Gelasio#10]
U+03B4 GREEK SMALL LETTER DELTA and U+03C9 GREEK SMALL LETTER OMEGA use the same glyphs as U+0394 GREEK CAPITAL LETTER DELTA and U+03A9 GREEK CAPITAL LETTER OMEGA.

**Comment by EbenSorkin** [comment]
I checked the unicodes you are referring to. You are correct. They are lower case. I'll look to find and fix this error in the source this coming week. Curious: did you discover this while doing technical comparisons of fonts or as a result of want to use those glyphs for something?

**Comment by dscorbett** [comment]
I found it while reviewing the font for bugs.

**Comment by EbenSorkin** [comment]
Thanks for finding it!

-e.

**Comment by EbenSorkin** [comment]
I have fixed the sources.
