### ISSUE TITLE
1.008 review

### ISSUE THREAD

**Issue by moyogo** [SorkinType/Gelasio#7]
# hturned, mturned
- ɥ and ɯ should have top serifs like u.
- ɯ should have a bottom terminal like u.
- ɥ should have serifs on descender like q, descender should be at descender-height.

<img width="879" alt="ɥɯ uq in Gelasio" src="https://github.com/SorkinType/Gelasio/assets/1923747/866b48b6-aa03-4c21-852c-2f2e5aa9b7de">

# Mturned

The uppercase can have multiple forms:
- scaled-up lowercase like in the Unicode charts
- Ш-shape like in Zhuang and Bouyei until it was replaced in 1981 by the letters W and E
- doubled U (UU ligature) used in older systems.

While the character was encoded for Zhuang and Bouyei, in Unicode and most fonts it doesn’t have the shape that was actually used (Ш-shape). In the mean time, the letter has been adopted in a couple of orthographies with the scaled-up lowercase shape.

With either form, the letter is typically wider than M or W, like Ш typically is.
It should definitely be wider here.

Compare for example WШM in Georgia
<img width="412" alt="WШM in Georgia" src="https://github.com/SorkinType/Gelasio/assets/1923747/88a027a1-2c64-40fc-813a-7feccfce16ab">

with WƜM in Gelasio
<img width="379" alt="WƜM in Gelasio Regular" src="https://github.com/SorkinType/Gelasio/assets/1923747/54abc2a0-83cd-432a-b75d-2092fe14b14f">

# Khook, Yhook

- ƘƳ should have more pronounced hooks, closer in orientation to the hook of J than the hook of ƁƊ or the lowercase letters. They don’t need to be as large as the hook of J.
<img width="786" alt="ƁƊ ƘƳJ Gelasio Bold" src="https://github.com/SorkinType/Gelasio/assets/1923747/fe5e73f0-3012-4b30-bf1d-0e03ce8888bc">
<img width="676" alt="ƁƊ ƘƳJ Gelasio Regular" src="https://github.com/SorkinType/Gelasio/assets/1923747/1cc8117a-d775-4bbb-b6bf-edbef067544f">

# yhook
ƴ in Gelasio Regular is a bit to thick on the stem before the hook terminal.
<img width="243" alt="279337589-a3c4f3ad-4f9f-4858-b5da-eab177658f3b" src="https://github.com/SorkinType/Gelasio/assets/1923747/d0878fcf-0406-4bcc-b82b-0380e7eda761">

The hook could probably by made more pronounced like for the capital. It could be raised a little bit. In context it is a bit too close to y so one of those too strategies would help.

# Oopen and oopen
- Ɔɔ are typically turned Cc, they may be inverted Cc in some documents but that is not the norm.
<img width="946" alt="cɔCƆ in Gelasio Bold" src="https://github.com/SorkinType/Gelasio/assets/1923747/fc1f2598-87ca-44bd-a405-d624152bfaf8">
<img width="818" alt="cɔCƆ in Gelasio Regular" src="https://github.com/SorkinType/Gelasio/assets/1923747/7d00a6f4-51f9-4927-aff6-5556cb14a837">

# Esh

Esh can have the ʃ-shape in Guinea languages or in Gabon languages. It’s not clear how much these orthographies are used but in Guinea it’s still the official national alphabet. The Sigma-shape was used in orthographies that don’t use the letter anymore (Ga before the 1960s or Xhosa before 1955).

I’d recommend using the ʃ-shape adjusted to caps.

# upsilon-latin

ʊ would fit better as a lowercase if it wasn’t a direct small-caps (or petite-caps) of its capital Ʊ.

For example
<img width="581" alt="ʊ in Gelasio Regular" src="https://github.com/SorkinType/Gelasio/assets/1923747/afa336d7-2278-49aa-b550-5822bea57d3c">

Compare in a word:
<img width="645" alt="Screenshot 2023-10-31 at 14 50 36" src="https://github.com/SorkinType/Gelasio/assets/1923747/04692773-1400-402c-96f1-675a9c815a08">

# Eng

The new default Eng is too narrow compare to other capitals and its right sidebearing is too narrow.
<img width="660" alt="Ŋ in Gelasio Regular" src="https://github.com/SorkinType/Gelasio/assets/1923747/e0b01175-cfee-412d-9423-6b92a7d133f3">
<img width="692" alt="Ŋ in Gelasio Bold" src="https://github.com/SorkinType/Gelasio/assets/1923747/9604c971-897d-4d8e-94a4-35b4860b4e11">

# Missing anchors

The following glyphs are letter and don’t have anchors:
```
Dcroat
Delta
Dtail
Dcroat
Delta
Eng
Esh
Eth
Germandbls
Mturned
OE
Omega
Saltillo
Schwa
Tbar
Thorn
Upsilon-latin
Vturned
bilabialclick
dcroat
dhook
eng
eth
eturned
germandbls
hbar
j
kgreenlandic
ldot
mu
obarred
pi
saltillo
tbar
thorn
upsilon-latin
vturned
```

/Schwa/schwa/eturned/Eng/eng/Mturned/mturned/obarred/OE/oe/Upsilon-latin/upsilon-latin/Vturned/vturned definitely need anchors as they are used with accents in orthographies. The others may as well in some transcription systems but are not top priority so it’s fine for now.

# Missing uppercase
The uppercase of some glyphs included is missing: /hturned/obarred.

# .loclMAH variants
/Lcommaaccent.loclMAH/lcommaaccent.loclMAH/Ncommaaccent.loclMAH/ncommaaccent.loclMAH should have a cedilla-shaped like the cedilla under O or M in Marshallese. Currently O and M get a "normal" cedilla but the .loclMAH use the same comma-shape cedilla as the Latvian letters.
<img width="750" alt="ĻļŅņ  Ḩḩ in Gelasio" src="https://github.com/SorkinType/Gelasio/assets/1923747/f9390718-31f8-482b-8652-b96ca14f0952">

Regenerate them with:
```
L+cedillacomb.case=Lcommaaccent.loclMAH
l+cedillacomb=lcommaaccent.loclMAH
N+cedillacomb.case=Ncommaaccent.loclMAH
n+cedillacomb=ncommaaccent.loclMAH
```
Optionally the cedillacomb could be centered on the stem like on Ḩ ḩ.
The Marshallese dictionary has it centered on the stem in some instances.

# Dutch NLD locl feature and /Jacute/jacute

The /Jacute/jacute NLD locl feature hack is a horrible practice.
It adds an acute on j when it follows an iacute in Dutch.
Users should use the combining acute with j if they want the acute on j.

The [spelling rule](https://woordenlijst.org/leidraad/5/1) clearly says the acute on j is usually omitted and shows an example.
Fonts with this hack cannot display the text of the rule itself in a meaningfull way.

Adding an acute when it’s not there breaks text that is intentionally spelled a certain way.
A third to a half of Dutch speakers spell with rules from before 1996 when putting two acutes became the norm, before that putting a single acute on vowels composed of different letters was very common. It still is common, it just doesn’t follow the non mandatory official rules.

Remove /Jacute/jacute and re-generate the locl feature.
Alternatively /Jacute/jacute could be renamed /J_acutecomb/j_acutecomb and a ligature substitution could be added but the ccmp feature already substitute j by jdotless when combined with top marks.

# calt feature
Remove the calt feature as it is.
```
sub Iacute Jacute by IJ_acutecomb;
sub I acute by Iacute;
sub J acute by Jacute;
sub iacute jacute by ij_acutecomb;
sub i acute by iacute;
sub j acute by jacute;
```
You don’t want the spacing acute to function like the combining acute. When used, the spacing acute is used as a spacing character.

You don’t want iacute jacute to form a ligature (single glyph).
Even if that were in the Dutch locl feature, that would be problematic in particular as i j are not substituted by ij in this font.

**Comment by moyogo** [comment]
For Gelasio-Italic, the same comments apply. Additionally:

# Bhook, Dhook

The hook seems larger than in Italic and Bold Italic masters than in Regular and Bold masters. This can be OK I guess, just making sure it is intentional.

**Comment by NeilSureshPatel** [comment]
Now that you have the alternate Eng you should 3 more Sami language tags in the locl feature to use the "capital N" style alternate.

```
    language ISM;
    sub Eng by Eng.loclNSM;
    language SKS;
    sub Eng by Eng.loclNSM;
    language LSM;
    sub Eng by Eng.loclNSM;
```

**Comment by EbenSorkin** [comment]
I have completed these fixes I think and added Ɛ Ʒ Ǯ Ǥ ɛ ʒ ǯ ǥ Please have a look.

**Comment by NeilSureshPatel** [comment]
It looks like you got all of the fixes from above with the exception of the following:

- The Capital Esh is still the Sigma style instead of an uppercase proportioned ʃ-shape.
- The right side of the ƴ  in the lower case does not appear to have been raised in the upright.
- OT code for alt Eng

# Open E
The Ɛ looks light and narrow in the regular upright. I can see the left side being about 20 units heavier, closer to the weight of the bowls of the B. In addition, whole character could be about 20 units wider.


<img width="643" alt="Screen Shot 2023-11-02 at 7 56 44 PM" src="https://github.com/SorkinType/Gelasio/assets/46502494/84ab829f-2c27-4beb-9af1-0dc416bd42de">

<img width="291" alt="Screen Shot 2023-11-02 at 7 59 25 PM" src="https://github.com/SorkinType/Gelasio/assets/46502494/0e163c99-b51d-4d30-b953-11194d4ca334">

**Comment by EbenSorkin** [comment]
I think these are all done now too. Thanks Neil!
